### ISSUE TITLE
Failed to load a language-javascript package grammar

### ISSUE THREAD

**Issue by aliengastianty** [atom/language-javascript#679]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [language-javascript](https://github.com/atom/language-javascript) package 0.134.1

### Stack Trace

Failed to load a language-javascript package grammar

```
At The specified module could not be found.
\\?\C:\Users\user\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\tree-sitter-javascript\build\Release\tree_sitter_javascript_binding.node in C:\Users\user\AppData\Local\atom\app-1.51.0\resources\app.asar\node_modules\language-javascript\grammars\tree-sitter-javascript.json

Error: The specified module could not be found.
\\?\C:\Users\user\AppData\Local\atom\app-1.51.0\resources\app.asar.unpacked\node_modules\tree-sitter-javascript\build\Release\tree_sitter_javascript_binding.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /app.asar/node_modules/tree-sitter-javascript/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-javascript/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:722026)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:3210648)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:360435)
    at ~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:360276
    at u (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:581084)
    at ~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:582337
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:483:5)
  at /app.asar/node_modules/language-javascript/grammars/tree-sitter-javascript.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
```

**Comment by icecream17** [comment]
I've noticed this is the same as issue #671, interesting
